### ISSUE TITLE
Gedcom won't load

### ISSUE THREAD

**Issue by shashgift** [nliautaud/gedcom-svg-fanchart#11]
Software worked fine year ago but now dropping a gedcom does nothing ("Drop a GEDCOM file" message doesn't disappear). Tried with multiple different .ged files. Tested both live version and repository.

**Comment by nliautaud** [comment]
It was an issue with the parser library host that died. That's fixed.
-> Switched cdn from wzrd.in to unpkg.com
-> Switched live deployment from rawgit to pages
