### ISSUE TITLE
Save the image

### ISSUE THREAD

**Issue by nigelhorne** [nliautaud/gedcom-svg-fanchart#6]
Can you please add a feature to download the image with the current pallette?

**Comment by nliautaud** [comment]
Hi, 
You should be able to export the chart in PDF using *print* in the browser : 
https://github.com/nliautaud/gedcom-svg-fanchart#saving--printing

That's a vector export that you can convert to any other format if needed.

**Comment by nliautaud** [comment]
Three saving / export options added & readme updated
